### ISSUE TITLE
[FEATURE] Remove Lucene 

### ISSUE THREAD

**Issue by philipreimer** [eclipse-opensmartclide/smartclide-context#14]
**Is your feature request related to a problem? Please describe.**
smartclide-context will not require indexing semi- or unstructured text because it will receive defined monitoring data messages from RMV component.
Therefore, the dependency on lucene is not needed.

**Describe the solution you'd like**
Work has already started in https://github.com/eclipse-researchlabs/smartclide/tree/removeLucene.
Move the current state of that branch to this repository - create a new branch here if needed - and create a PR.

Remove the original branch https://github.com/eclipse-researchlabs/smartclide/tree/removeLucene

**Comment by philipreimer** [comment]
@horozal this might be helpful: https://kasunsiyambalapitiya.medium.com/move-git-branch-from-one-repository-to-another-with-preserving-history-81ed64de3a02

**Comment by horozal** [comment]
Done: https://github.com/eclipse-researchlabs/smartclide-context/tree/removeLucene

**Comment by philipreimer** [comment]
@horozal please also create a PR for the new branch.

This will require some changes in the branch because files in [removeLucene](/eclipse-researchlabs/smartclide-context/tree/removeLucene) are still located in the `context` directory, which does not exist anymore in this repository.

**Comment by schlotze** [comment]
decided to keep lucene for now
